[package]
name = "phx-market"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
phx-core = { path = "../phx-core" }
phx-geo = { path = "../phx-geo" }
phx-id = { path = "../../foundation/phx-id" }
phx-ledger = { path = "../phx-ledger" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-num = { path = "../../foundation/phx-num" }
phx-rand = { path = "../../foundation/phx-rand" }
phx-store = { path = "../phx-store" }
libm.workspace = true

[dev-dependencies]
gungraun.workspace = true

[lints]
workspace = true

[[bench]]
name = "linked_call"
harness = false
