use std::any::Any;
use std::marker::PhantomData;

use phx_id::{Date, Day, PartyId, Slot};
use phx_macros::clause;
use phx_num::{Missing, violation};
use phx_rand::{Draws, Subject};

use crate::decisions::{Decider, DecisionPointDecl, PlayerQueue, QueuedPayload, dispatch};
use crate::facts::FactDef;
use crate::register::Register;
use crate::register::limit::{Bindings, Bound, Limited};
use crate::rules::{RuleSig, RuleTable};
use crate::streams::{Purpose, StreamDef, Streams};
use crate::substep::SubStep;

/// A handler's body over one chunk: its context built from the day's parts, then the body for each row of the chunk.
pub type RunChunk = fn(CtxParts<'_, dyn FactStore>, core::ops::Range<u32>);

/// A handler's declaration, generated by `declare_handler!`: its sub-step, its table, by name what it reads, writes
/// directly, emits and draws, which the marker traits below repeat as types, and its body.
pub trait HandlerDecl: 'static {
    const NAME: &'static str;
    const SUBSTEP: SubStep;
    const TABLE: &'static str;
    const READS: &'static [&'static str];
    const WRITES: &'static [&'static str];
    const INTENTS: &'static [&'static str];
    const STREAMS: &'static [&'static str];
    const CLAUSE: &'static str;
    const RUN: Missing<RunChunk>;
}

/// The handler reads the fact.
pub trait Reads<F: FactDef> {}
/// The handler writes the fact on its own rows, directly.
pub trait Writes<F: FactDef> {}
/// The handler emits the intent, applied at its sub-step's apply point.
pub trait Emits<I: IntentDef> {}
/// The handler draws from the stream.
pub trait DrawsFrom<S: StreamDef> {}

/// An effect on anything but the handler's own directly written columns, gathered and applied at the apply point.
pub trait IntentDef {
    const NAME: &'static str;
    fn encode(&self, out: &mut Vec<u64>);
}

/// A handler's intents, in the order it emitted them: each its kind and its words.
#[derive(Debug, Default)]
pub struct Intents {
    words: Vec<u64>,
    items: Vec<(&'static str, usize, usize)>,
}

impl Intents {
    fn push<I: IntentDef>(&mut self, intent: &I) {
        let start = self.words.len();
        intent.encode(&mut self.words);
        self.items.push((I::NAME, start, self.words.len() - start));
    }

    /// Each intent's kind and words, in emission order.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &[u64])> + '_ {
        self.items.iter().filter_map(|(name, start, len)| self.words.get(*start..start + len).map(|w| (*name, w)))
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.items.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }
}

/// The rows a handler sees: their facts at the sub-step's start, and the handler's own direct writes. A read takes the
/// store mutably so that a traced chunk can record what it read.
pub trait FactStore {
    fn read(&mut self, fact: &'static str, slot: Slot) -> Missing<i64>;
    fn write(&mut self, fact: &'static str, slot: Slot, value: i64);
}

/// A stream opened on a traced chunk: its name and subject.
pub type Opened = (&'static str, u64);

/// What the day gives every handler's context: the register, and the state its own system compiled at assembly,
/// which only that system's handlers are given; `opens` is present on a traced chunk.
#[derive(Debug)]
pub struct CtxParts<'a, S: FactStore + ?Sized> {
    pub day: Day,
    pub date: Date,
    pub streams: &'a Streams,
    pub register: &'a Register,
    pub own: &'a (dyn Any + Send + Sync),
    pub facts: &'a mut S,
    pub intents: &'a mut Intents,
    pub bindings: &'a mut Bindings,
    pub rules: &'a RuleTable,
    pub queue: &'a mut PlayerQueue,
    pub opens: Option<&'a mut Vec<Opened>>,
}

/// A handler's context, granting exactly what its declaration lists: reading an undeclared fact, writing an undeclared
/// column, emitting an undeclared intent or drawing from an undeclared stream does not compile.
#[clause("TIME.6")]
#[derive(Debug)]
pub struct Ctx<'a, H: HandlerDecl, S: FactStore + ?Sized> {
    parts: CtxParts<'a, S>,
    handler: PhantomData<H>,
}

impl<'a, H: HandlerDecl, S: FactStore + ?Sized> Ctx<'a, H, S> {
    #[doc(hidden)]
    #[must_use]
    pub fn new(parts: CtxParts<'a, S>) -> Ctx<'a, H, S> {
        Ctx { parts, handler: PhantomData }
    }

    pub fn day(&self) -> Day {
        self.parts.day
    }

    /// The day's civil date.
    pub fn date(&self) -> Date {
        self.parts.date
    }

    #[must_use]
    pub fn substep(&self) -> SubStep {
        H::SUBSTEP
    }

    pub fn read<F: FactDef>(&mut self, slot: Slot) -> Missing<i64>
    where
        H: Reads<F>,
    {
        self.parts.facts.read(F::ITEM.name, slot)
    }

    pub fn write<F: FactDef>(&mut self, slot: Slot, value: i64)
    where
        H: Writes<F>,
    {
        self.parts.facts.write(F::ITEM.name, slot, value);
    }

    pub fn emit<I: IntentDef>(&mut self, intent: &I)
    where
        H: Emits<I>,
    {
        self.parts.intents.push(intent);
    }

    /// The register, whose primitives a handler reads through the handles its system keeps.
    #[must_use]
    pub fn register(&self) -> &'a Register {
        self.parts.register
    }

    /// The state the handler's own system compiled at assembly.
    #[must_use]
    pub fn own<T: Any>(&self) -> &'a T {
        let Some(own) = self.parts.own.downcast_ref::<T>() else {
            violation!(clause = "Law 4", "a handler reading state its system did not compile");
        };
        own
    }

    /// The stream's draws for a subject at this day and sub-step; the observer's streams are never the world's.
    #[must_use]
    pub fn draws<T: StreamDef>(&mut self, subject: Subject) -> Draws
    where
        H: DrawsFrom<T>,
    {
        if T::DECL.purpose == Purpose::Observer {
            violation!(clause = "Law 17", "a handler drawing from the observer's stream");
        }
        if let Some(opens) = self.parts.opens.as_deref_mut() {
            opens.push((T::DECL.name, subject.raw()));
        }
        if T::DECL.keyed {
            return self.parts.streams.open_keyed(&T::DECL, subject);
        }
        self.parts.streams.open(&T::DECL, subject, self.parts.day, H::SUBSTEP.ordinal())
    }

    /// What a limit left of a want, recording the binding the party will see when there was an excess.
    pub fn bound<T: Limited>(&mut self, party: PartyId, bound: Bound<T>) -> T {
        self.parts.bindings.take(party, self.parts.day, bound)
    }

    /// A rule handle's answer.
    pub fn rule<I: 'static, O: 'static>(&self, sig: RuleSig<I, O>, input: &I) -> O {
        self.parts.rules.call(sig, input)
    }

    /// A party's decision at a point: the player's queued intent, the rule, or none.
    pub fn decide<I, O: QueuedPayload>(
        &mut self,
        point: &DecisionPointDecl<I, O>,
        party: PartyId,
        decider: Decider,
        input: &I,
    ) -> Option<O> {
        let queued = match decider {
            Decider::Player { .. } => self.parts.queue.take(party, point.name),
            Decider::Rule => None,
        };
        dispatch(point, decider, queued.as_deref(), input)
    }
}

#[cfg(test)]
pub(crate) mod testing {
    use phx_id::Slot;
    use phx_num::Missing;

    use super::FactStore;

    /// Facts as a list of (fact, slot, value), for tests of what a context passes through.
    #[derive(Debug, Default)]
    pub struct ListFacts {
        pub values: Vec<(&'static str, Slot, i64)>,
    }

    impl FactStore for ListFacts {
        fn read(&mut self, fact: &'static str, slot: Slot) -> Missing<i64> {
            self.values
                .iter()
                .rev()
                .find(|(f, s, _)| *f == fact && *s == slot)
                .map_or(Missing::Absent, |v| Missing::Present(v.2))
        }

        fn write(&mut self, fact: &'static str, slot: Slot, value: i64) {
            self.values.push((fact, slot, value));
        }
    }
}

#[cfg(test)]
mod tests {
    use phx_id::{Day, PartyId, Slot};
    use phx_num::{Amount, Missing};
    use phx_rand::{Seed, Subject, SubjectTag};

    use super::testing::ListFacts;
    use super::{Ctx, CtxParts, DrawsFrom, Emits, HandlerDecl, IntentDef, Intents, Reads, Writes};
    use crate::decisions::PlayerQueue;
    use crate::facts::{Audience, FactDecl, FactDef, FactType, ItemDecl, ItemKind, ReprClass, Writer};
    use crate::register::limit::{Bindings, DeclaredLimit, TermsToken};
    use crate::rules::RuleTable;
    use crate::streams::{Purpose, StreamDecl, StreamDef, Streams};
    use crate::substep::SubStep;

    struct Income;
    impl FactDef for Income {
        const ITEM: ItemDecl = ItemDecl {
            name: "HH.income",
            kind: ItemKind::Fact(FactDecl {
                value: FactType::Money,
                unit: Missing::Absent,
                kinds: &["household"],
                audience: Audience::Party,
                repr: ReprClass::Position,
            }),
            writer: Writer::System("HH"),
            clause: "HH.1",
        };
    }

    struct Tracer;
    impl StreamDef for Tracer {
        const DECL: StreamDecl =
            StreamDecl { name: "OBS.tracer", purpose: Purpose::Observer, keyed: false, clause: "OBS.8" };
    }

    struct Offer(u64);
    impl IntentDef for Offer {
        const NAME: &'static str = "LAB.offer";
        fn encode(&self, out: &mut Vec<u64>) {
            out.push(self.0);
        }
    }

    struct Hire;
    impl HandlerDecl for Hire {
        const NAME: &'static str = "LAB.hire";
        const SUBSTEP: SubStep = SubStep::S5c;
        const TABLE: &'static str = "household";
        const READS: &'static [&'static str] = &["HH.income"];
        const WRITES: &'static [&'static str] = &["HH.income"];
        const INTENTS: &'static [&'static str] = &["LAB.offer"];
        const STREAMS: &'static [&'static str] = &["OBS.tracer"];
        const CLAUSE: &'static str = "LAB.9";
        const RUN: Missing<super::RunChunk> = Missing::Absent;
    }
    impl Reads<Income> for Hire {}
    impl Writes<Income> for Hire {}
    impl Emits<Offer> for Hire {}
    impl DrawsFrom<Tracer> for Hire {}

    #[test]
    fn ctx_passes_through_what_the_handler_declares() {
        let streams = Streams::new(Seed::new(1), &[Tracer::DECL]).unwrap();
        let (mut facts, mut intents, mut bindings, mut queue) =
            (ListFacts::default(), Intents::default(), Bindings::default(), PlayerQueue::unseated());
        let rules = RuleTable::default();
        let register = crate::register::RegisterBuilder::default().build(&[], 1).unwrap();
        let mut opens = Vec::new();
        let parts = CtxParts {
            day: Day::new(4),
            date: phx_id::Date::new(2025, 1, 5).unwrap(),
            streams: &streams,
            register: &register,
            own: &7_u32,
            facts: &mut facts,
            intents: &mut intents,
            bindings: &mut bindings,
            rules: &rules,
            queue: &mut queue,
            opens: Some(&mut opens),
        };
        let mut ctx: Ctx<'_, Hire, ListFacts> = Ctx::new(parts);
        let row = Slot::new(2);
        assert_eq!(ctx.read::<Income>(row), Missing::Absent);
        ctx.write::<Income>(row, 900);
        assert_eq!(ctx.read::<Income>(row), Missing::Present(900));
        ctx.emit(&Offer(5));
        let limit = DeclaredLimit::from_terms(TermsToken::new(), Amount::from_raw(10));
        assert_eq!(ctx.bound(PartyId::new(1), limit.bind(Amount::from_raw(15))), Amount::from_raw(10));
        let subject = Subject::new(SubjectTag::Party, 1);
        let caught = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ctx.draws::<Tracer>(subject)));
        assert!(caught.is_err(), "a handler never draws from the observer's stream");
        assert_eq!((ctx.substep(), ctx.day(), *ctx.own::<u32>()), (SubStep::S5c, Day::new(4), 7));
        let wrong = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| *ctx.own::<u64>()));
        assert!(wrong.is_err(), "a handler reads only its own system's state, by its type");
        assert_eq!(intents.iter().collect::<Vec<_>>(), vec![("LAB.offer", &[5_u64][..])]);
        assert_eq!(bindings.drain().count(), 1);
    }
}
