use std::any::Any;
use std::marker::PhantomData;

use phx_id::{Date, Day, PartyId, PartyKey, Slot};
use phx_macros::clause;
use phx_num::{Missing, violation};
use phx_rand::{Draws, Subject};

use crate::decisions::{Decider, DecisionPointDecl, PlayerQueue, QueuedPayload, dispatch};
use crate::facts::FactDef;
use crate::flows::{Denom, Flow};
use crate::register::Register;
use crate::register::limit::{Bindings, Bound, Limited};
use crate::rules::{RuleSig, RuleTable};
use crate::streams::{Purpose, StreamDef, Streams};
use crate::substep::SubStep;

/// A handler's body over one chunk: its context built from the day's parts, then the body for each row of the chunk.
pub type RunChunk = fn(CtxParts<'_, dyn FactStore>, core::ops::Range<u32>);

/// A handler's declaration, generated by `declare_handler!`: its sub-step, its table, by name what it reads, writes
/// directly, emits and draws, which the marker traits below repeat as types, and its body.
pub trait HandlerDecl: 'static {
    const NAME: &'static str;
    const SUBSTEP: SubStep;
    const TABLE: &'static str;
    const READS: &'static [&'static str];
    const WRITES: &'static [&'static str];
    const INTENTS: &'static [&'static str];
    const STREAMS: &'static [&'static str];
    const CLAUSE: &'static str;
    const RUN: Missing<RunChunk>;
}

/// The handler reads the fact.
pub trait Reads<F: FactDef> {}
/// The handler writes the fact on its own rows, directly.
pub trait Writes<F: FactDef> {}
/// The handler emits the intent, applied at its sub-step's apply point.
pub trait Emits<I: IntentDef> {}
/// The handler draws from the stream.
pub trait DrawsFrom<S: StreamDef> {}

/// A reason money or units move for, declared once: the code its flows carry, which says the lines they post to, and
/// the payment order a payer's flows of it keep among its others.
#[clause("MON.5", "SET.4")]
pub trait ReasonDef: 'static {
    const CODE: u8;
    const ORDER: u8;
}

/// A handler that pays for a reason: its context makes flows of that reason and of no other.
pub trait Pays<R: ReasonDef> {}

/// An effect on anything but the handler's own directly written columns, gathered and applied at the apply point.
pub trait IntentDef {
    const NAME: &'static str;
    fn encode(&self, out: &mut Vec<u64>);
}

/// A handler's intents, in the order it emitted them: each its kind and its words.
#[derive(Debug, Default)]
pub struct Intents {
    words: Vec<u64>,
    items: Vec<(&'static str, usize, usize)>,
}

impl Intents {
    fn push<I: IntentDef>(&mut self, intent: &I) {
        let start = self.words.len();
        intent.encode(&mut self.words);
        self.items.push((I::NAME, start, self.words.len() - start));
    }

    /// Another's intents after these, in their order.
    pub fn append(&mut self, other: Intents) {
        let shift = self.words.len();
        self.words.extend(other.words);
        self.items.extend(other.items.into_iter().map(|(name, start, len)| (name, start + shift, len)));
    }

    /// Each intent's kind and words, in emission order.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &[u64])> + '_ {
        self.items.iter().filter_map(|(name, start, len)| self.words.get(*start..start + len).map(|w| (*name, w)))
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.items.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }
}

/// The rows a handler sees: their facts at the sub-step's start, and the handler's own direct writes. A read takes the
/// store mutably so that a traced chunk can record what it read.
pub trait FactStore {
    fn read(&mut self, fact: &'static str, slot: Slot) -> Missing<i64>;
    fn write(&mut self, fact: &'static str, slot: Slot, value: i64);
}

/// A table's facts read without recording the read, as rows visited on the pool read them.
pub trait FactRead: Sync {
    fn peek(&self, fact: &'static str, slot: Slot) -> Missing<i64>;
}

/// A shard of a visit's rows: the facts its handler declares, read from the table before it runs, and the handler's
/// writes kept aside, a row reading back what it wrote, until they are written to the table in the rows' order once
/// every shard has run. A row reads and writes only its own declared facts, so no shard sees another's writes.
#[derive(Debug)]
pub struct FactOverlay {
    facts: Vec<&'static str>,
    slots: Vec<Slot>,
    values: Vec<Missing<i64>>,
    writes: Vec<(Slot, &'static str, i64)>,
}

impl FactOverlay {
    /// The declared `facts` of the rows at `slots`, in the slots' order, read from `base`.
    #[must_use]
    pub fn read_from(base: &dyn FactRead, facts: Vec<&'static str>, slots: &[Slot]) -> FactOverlay {
        let values = slots.iter().flat_map(|s| facts.iter().map(move |f| base.peek(f, *s))).collect();
        FactOverlay { facts, slots: slots.to_vec(), values, writes: Vec::new() }
    }

    /// The writes kept, in the order they were made.
    #[must_use]
    pub fn into_writes(self) -> Vec<(Slot, &'static str, i64)> {
        self.writes
    }

    fn at(&self, fact: &'static str, slot: Slot) -> usize {
        let (Ok(row), Some(f)) = (self.slots.binary_search(&slot), self.facts.iter().position(|x| *x == fact)) else {
            violation!(
                clause = "TIME.6",
                "a handler on the pool read a row or fact outside its shard's",
                slot = slot.get()
            );
        };
        row * self.facts.len() + f
    }
}

impl FactStore for FactOverlay {
    fn read(&mut self, fact: &'static str, slot: Slot) -> Missing<i64> {
        let at = self.at(fact, slot);
        self.values.get(at).copied().unwrap_or(Missing::Absent)
    }

    fn write(&mut self, fact: &'static str, slot: Slot, value: i64) {
        let at = self.at(fact, slot);
        if let Some(v) = self.values.get_mut(at) {
            *v = Missing::Present(value);
        }
        self.writes.push((slot, fact, value));
    }
}

/// A deposit whose right a row's party holds, as the holder sees it: the deposit's place in the map's list, the
/// product extracted from it, the zone its goods stand at once taken, its grade in thousandths, and what it held at the
/// opening and holds still, none for a deposit without end.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HeldRight {
    pub deposit: u32,
    pub product: u16,
    pub zone: u32,
    pub grade: i64,
    pub opening: Missing<i64>,
    pub remaining: Missing<i64>,
}

/// A good a row holds: its product, its grade class and its units.
pub type HeldGood = (u16, u8, i64);

/// Plant a row holds: its kind, its condition class and its units.
pub type HeldPlant = (u8, u8, i64);

/// A good a row holds at another place than its own: its product, its grade class, the zone, its units there, and
/// those free of other claims, as goods on their way are not.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HeldAway {
    pub product: u16,
    pub grade: u8,
    pub zone: u32,
    pub units: i64,
    pub free: i64,
}

/// A place a good could be carried to or bought at from where a row stands, as the public prices show it: the zone,
/// the mode, the metres between, the good's mark there for a lot, and the freight of a lot of the good by the mode
/// from the row's place to there at the lowest price carriage is posted at here, and from there to the row's place at
/// the lowest posted there; each none where the mode's carriage is posted at neither end.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Away {
    pub zone: u32,
    pub mode: u16,
    pub metres: u64,
    pub there: i64,
    pub outbound: Missing<i64>,
    pub inbound: Missing<i64>,
}

/// What a row's party may read of goods beyond its facts: its free units of each good at its place, those not pledged or
/// committed, and the list of them; the deposits whose rights it holds; the units of a product, of every grade, it has
/// delivered since the world opened; and each good's latest mark at its place and the public outlook of its price
/// there by a method, which are public.
pub trait GoodsView: core::fmt::Debug {
    fn held(&self, slot: Slot, product: u16, grade: u8) -> i64;
    fn goods(&self, slot: Slot) -> &[HeldGood];
    fn rights(&self, slot: Slot) -> &[HeldRight];
    fn delivered(&self, slot: Slot, product: u16) -> i64;
    fn mark(&self, slot: Slot, product: u16, grade: u8) -> Missing<i64>;
    /// The price a product last sold at, for a lot, at retail in the row's country: the market's mark.
    fn posted(&self, slot: Slot, product: u16) -> Missing<i64>;
    /// A method's record on the series a stance over a product reads — its market between firms where the row stands,
    /// or else its country's retail market — in millionths; none before the method's first surprise there.
    fn record(&self, slot: Slot, product: u16, method: u16) -> Missing<i64>;
    /// The party the row is, as a subject a draw of its own is keyed by.
    fn party(&self, slot: Slot) -> Missing<phx_id::PartyId>;
    fn outlook(&self, slot: Slot, product: u16, grade: u8, method: u16) -> Missing<i64>;
    /// The money the row's party holds on its account; none without an account.
    fn money(&self, slot: Slot) -> Missing<i64>;
    /// The hours a week the row's party's employees work for it, as its employment lines hold them.
    fn staff_hours(&self, slot: Slot) -> Missing<i64>;
    /// The country the row stands in.
    fn country(&self, slot: Slot) -> Missing<phx_id::CountryId>;
    /// Whether the good's market where the row stands last met with no seller.
    fn unsold(&self, slot: Slot, product: u16, grade: u8) -> bool;
    /// The grade classes a product is marked in at some place, in their order.
    fn grades(&self, product: u16) -> Vec<u8>;
    /// The zone the row stands in.
    fn zone(&self, slot: Slot) -> Missing<u32>;
    /// The goods the row holds at other places than its own.
    fn elsewhere(&self, slot: Slot) -> &[HeldAway];
    /// The plant the row holds.
    fn plant(&self, slot: Slot) -> &[HeldPlant];
    /// The other places in the row's country a good is marked at, by each mode carriage is marked in where it stands.
    fn away(&self, slot: Slot, product: u16, grade: u8) -> Vec<Away>;
    /// What winding the row's party down would return beyond the money it keeps either way: its goods less what it
    /// owes.
    fn net_assets(&self, slot: Slot) -> Missing<i64>;
}

/// The view of rows that hold no goods, as a kernel table's are.
#[derive(Clone, Copy, Debug, Default)]
pub struct NoGoods;

impl GoodsView for NoGoods {
    fn held(&self, _: Slot, _: u16, _: u8) -> i64 {
        0
    }
    fn goods(&self, _: Slot) -> &[HeldGood] {
        &[]
    }
    fn rights(&self, _: Slot) -> &[HeldRight] {
        &[]
    }
    fn delivered(&self, _: Slot, _: u16) -> i64 {
        0
    }
    fn mark(&self, _: Slot, _: u16, _: u8) -> Missing<i64> {
        Missing::Absent
    }
    fn posted(&self, _: Slot, _: u16) -> Missing<i64> {
        Missing::Absent
    }
    fn record(&self, _: Slot, _: u16, _: u16) -> Missing<i64> {
        Missing::Absent
    }
    fn party(&self, _: Slot) -> Missing<phx_id::PartyId> {
        Missing::Absent
    }
    fn outlook(&self, _: Slot, _: u16, _: u8, _: u16) -> Missing<i64> {
        Missing::Absent
    }
    fn money(&self, _: Slot) -> Missing<i64> {
        Missing::Absent
    }
    fn staff_hours(&self, _: Slot) -> Missing<i64> {
        Missing::Absent
    }
    fn country(&self, _: Slot) -> Missing<phx_id::CountryId> {
        Missing::Absent
    }
    fn unsold(&self, _: Slot, _: u16, _: u8) -> bool {
        false
    }
    fn grades(&self, _: u16) -> Vec<u8> {
        Vec::new()
    }
    fn zone(&self, _: Slot) -> Missing<u32> {
        Missing::Absent
    }
    fn elsewhere(&self, _: Slot) -> &[HeldAway] {
        &[]
    }
    fn plant(&self, _: Slot) -> &[HeldPlant] {
        &[]
    }
    fn away(&self, _: Slot, _: u16, _: u8) -> Vec<Away> {
        Vec::new()
    }
    fn net_assets(&self, _: Slot) -> Missing<i64> {
        Missing::Absent
    }
}

/// A stream opened on a traced chunk: its name and subject.
pub type Opened = (&'static str, u64);

/// What the day gives every handler's context: the register, and the state its own system compiled at assembly,
/// which only that system's handlers are given; `opens` is present on a traced chunk.
#[derive(Debug)]
pub struct CtxParts<'a, S: FactStore + ?Sized> {
    pub day: Day,
    pub date: Date,
    pub streams: &'a Streams,
    pub register: &'a Register,
    pub own: &'a (dyn Any + Send + Sync),
    pub facts: &'a mut S,
    pub goods: &'a dyn GoodsView,
    pub intents: &'a mut Intents,
    pub bindings: &'a mut Bindings,
    pub rules: &'a RuleTable,
    pub queue: &'a mut PlayerQueue,
    pub opens: Option<&'a mut Vec<Opened>>,
    /// The chunk's flow buffer, in a sub-step whose flows the day settles.
    pub flows: Option<&'a mut Vec<Flow>>,
}

/// A handler's context, granting exactly what its declaration lists: reading an undeclared fact, writing an undeclared
/// column, emitting an undeclared intent or drawing from an undeclared stream does not compile.
#[clause("TIME.6")]
#[derive(Debug)]
pub struct Ctx<'a, H: HandlerDecl, S: FactStore + ?Sized> {
    parts: CtxParts<'a, S>,
    handler: PhantomData<H>,
}

impl<'a, H: HandlerDecl, S: FactStore + ?Sized> Ctx<'a, H, S> {
    #[doc(hidden)]
    #[must_use]
    pub fn new(parts: CtxParts<'a, S>) -> Ctx<'a, H, S> {
        Ctx { parts, handler: PhantomData }
    }

    pub fn day(&self) -> Day {
        self.parts.day
    }

    /// The day's civil date.
    pub fn date(&self) -> Date {
        self.parts.date
    }

    #[must_use]
    pub fn substep(&self) -> SubStep {
        H::SUBSTEP
    }

    pub fn read<F: FactDef>(&mut self, slot: Slot) -> Missing<i64>
    where
        H: Reads<F>,
    {
        self.parts.facts.read(F::ITEM.name, slot)
    }

    pub fn write<F: FactDef>(&mut self, slot: Slot, value: i64)
    where
        H: Writes<F>,
    {
        self.parts.facts.write(F::ITEM.name, slot, value);
    }

    /// The row's party's free units of a good at its place: what it holds less what is pledged or committed.
    #[must_use]
    pub fn held(&self, slot: Slot, product: u16, grade: u8) -> i64 {
        self.parts.goods.held(slot, product, grade)
    }

    /// Every good the row's party holds at its place.
    #[must_use]
    pub fn goods(&self, slot: Slot) -> &[HeldGood] {
        self.parts.goods.goods(slot)
    }

    /// The plant a row holds, by kind and condition class.
    #[must_use]
    pub fn plant(&self, slot: Slot) -> &[HeldPlant] {
        self.parts.goods.plant(slot)
    }

    /// What winding the row's party down would return.
    pub fn net_assets(&self, slot: Slot) -> Missing<i64> {
        self.parts.goods.net_assets(slot)
    }

    /// The other places a good is marked at and the carriage from the row's place to them, as the public prices show.
    #[must_use]
    pub fn away(&self, slot: Slot, product: u16, grade: u8) -> Vec<Away> {
        self.parts.goods.away(slot, product, grade)
    }

    /// The public outlook of a good's price at the row's place by a method, in its market's raw price.
    pub fn outlook(&self, slot: Slot, product: u16, grade: u8, method: u16) -> Missing<i64> {
        self.parts.goods.outlook(slot, product, grade, method)
    }

    /// The deposits whose rights the row's party holds.
    #[must_use]
    pub fn rights(&self, slot: Slot) -> &[HeldRight] {
        self.parts.goods.rights(slot)
    }

    /// The units of a product, of every grade, the row's party has delivered since the world opened.
    #[must_use]
    pub fn delivered(&self, slot: Slot, product: u16) -> i64 {
        self.parts.goods.delivered(slot, product)
    }

    /// The money the row's party holds on its account.
    pub fn money(&self, slot: Slot) -> Missing<i64> {
        self.parts.goods.money(slot)
    }

    /// The hours a week the row's party's employees work for it.
    pub fn staff_hours(&self, slot: Slot) -> Missing<i64> {
        self.parts.goods.staff_hours(slot)
    }

    /// The country the row stands in.
    pub fn country(&self, slot: Slot) -> Missing<phx_id::CountryId> {
        self.parts.goods.country(slot)
    }

    /// Whether the good's market where the row stands last met with no seller.
    #[must_use]
    pub fn unsold(&self, slot: Slot, product: u16, grade: u8) -> bool {
        self.parts.goods.unsold(slot, product, grade)
    }

    /// The grade classes a product is marked in at some place, in their order.
    #[must_use]
    pub fn grades(&self, product: u16) -> Vec<u8> {
        self.parts.goods.grades(product)
    }

    /// The zone the row stands in.
    pub fn zone(&self, slot: Slot) -> Missing<u32> {
        self.parts.goods.zone(slot)
    }

    /// The goods the row holds at other places than its own.
    #[must_use]
    pub fn elsewhere(&self, slot: Slot) -> &[HeldAway] {
        self.parts.goods.elsewhere(slot)
    }

    /// A good's latest mark at the row's place, in its market's raw price.
    pub fn mark(&self, slot: Slot, product: u16, grade: u8) -> Missing<i64> {
        self.parts.goods.mark(slot, product, grade)
    }

    pub fn posted(&self, slot: Slot, product: u16) -> Missing<i64> {
        self.parts.goods.posted(slot, product)
    }

    pub fn record(&self, slot: Slot, product: u16, method: u16) -> Missing<i64> {
        self.parts.goods.record(slot, product, method)
    }

    pub fn party(&self, slot: Slot) -> Missing<phx_id::PartyId> {
        self.parts.goods.party(slot)
    }

    pub fn emit<I: IntentDef>(&mut self, intent: &I)
    where
        H: Emits<I>,
    {
        self.parts.intents.push(intent);
    }

    /// A flow for a reason the handler declares: from the payer to the payee, an amount of a denomination, from a
    /// source the reason names, in the reason's payment order. A flow runs from its payer, so a negative amount is
    /// refused.
    pub fn flow<R: ReasonDef>(&mut self, sides: [PartyKey; 2], amount: i64, denomination: Denom, source: u32)
    where
        H: Pays<R>,
    {
        if amount < 0 {
            violation!(clause = "Law 5", "a flow of a negative amount", amount = amount);
        }
        let Some(buf) = self.parts.flows.as_deref_mut() else {
            violation!(clause = "TIME.6", "a flow made in a sub-step that settles none");
        };
        let [from, to] = sides;
        buf.push(Flow { payer: from, payee: to, amount, source, denomination, reason: R::CODE, order: R::ORDER });
    }

    /// The register, whose primitives a handler reads through the handles its system keeps.
    #[must_use]
    pub fn register(&self) -> &'a Register {
        self.parts.register
    }

    /// The state the handler's own system compiled at assembly.
    #[must_use]
    pub fn own<T: Any>(&self) -> &'a T {
        let Some(own) = self.parts.own.downcast_ref::<T>() else {
            violation!(clause = "Law 4", "a handler reading state its system did not compile");
        };
        own
    }

    /// The stream's draws for a subject at this day and sub-step; the observer's streams are never the world's.
    #[must_use]
    pub fn draws<T: StreamDef>(&mut self, subject: Subject) -> Draws
    where
        H: DrawsFrom<T>,
    {
        if T::DECL.purpose == Purpose::Observer {
            violation!(clause = "Law 17", "a handler drawing from the observer's stream");
        }
        if let Some(opens) = self.parts.opens.as_deref_mut() {
            opens.push((T::DECL.name, subject.raw()));
        }
        if T::DECL.keyed {
            return self.parts.streams.open_keyed(&T::DECL, subject);
        }
        self.parts.streams.open(&T::DECL, subject, self.parts.day, H::SUBSTEP.ordinal())
    }

    /// What a limit left of a want, recording the binding the party will see when there was an excess.
    pub fn bound<T: Limited>(&mut self, party: PartyId, bound: Bound<T>) -> T {
        self.parts.bindings.take(party, self.parts.day, bound)
    }

    /// A rule handle's answer.
    pub fn rule<I: 'static, O: 'static>(&self, sig: RuleSig<I, O>, input: &I) -> O {
        self.parts.rules.call(sig, input)
    }

    /// A party's decision at a point: the player's queued intent, the rule, or none.
    pub fn decide<I, O: QueuedPayload>(
        &mut self,
        point: &DecisionPointDecl<I, O>,
        party: PartyId,
        decider: Decider,
        input: &I,
    ) -> Option<O> {
        let queued = match decider {
            Decider::Player { .. } => self.parts.queue.take(party, point.name),
            Decider::Rule => None,
        };
        dispatch(point, decider, queued.as_deref(), input)
    }
}

#[cfg(test)]
pub(crate) mod testing {
    use phx_id::Slot;
    use phx_num::Missing;

    use super::FactStore;

    /// Facts as a list of (fact, slot, value), for tests of what a context passes through.
    #[derive(Debug, Default)]
    pub struct ListFacts {
        pub values: Vec<(&'static str, Slot, i64)>,
    }

    impl FactStore for ListFacts {
        fn read(&mut self, fact: &'static str, slot: Slot) -> Missing<i64> {
            self.values
                .iter()
                .rev()
                .find(|(f, s, _)| *f == fact && *s == slot)
                .map_or(Missing::Absent, |v| Missing::Present(v.2))
        }

        fn write(&mut self, fact: &'static str, slot: Slot, value: i64) {
            self.values.push((fact, slot, value));
        }
    }
}

#[cfg(test)]
mod tests {
    use phx_id::{Day, PartyId, Slot};
    use phx_num::{Amount, Missing};
    use phx_rand::{Seed, Subject, SubjectTag};

    use super::testing::ListFacts;
    use super::{Ctx, CtxParts, DrawsFrom, Emits, HandlerDecl, IntentDef, Intents, Reads, Writes};
    use crate::decisions::PlayerQueue;
    use crate::facts::{Audience, FactDecl, FactDef, FactType, ItemDecl, ItemKind, ReprClass, Writer};
    use crate::register::limit::{Bindings, DeclaredLimit, TermsToken};
    use crate::rules::RuleTable;
    use crate::streams::{Purpose, StreamDecl, StreamDef, Streams};
    use crate::substep::SubStep;

    struct Income;
    impl FactDef for Income {
        const ITEM: ItemDecl = ItemDecl {
            name: "HH.income",
            kind: ItemKind::Fact(FactDecl {
                value: FactType::Money,
                unit: Missing::Absent,
                kinds: &["household"],
                audience: Audience::Party,
                repr: ReprClass::Position,
            }),
            writer: Writer::System("HH"),
            clause: "HH.1",
        };
    }

    struct Tracer;
    impl StreamDef for Tracer {
        const DECL: StreamDecl =
            StreamDecl { name: "OBS.tracer", purpose: Purpose::Observer, keyed: false, clause: "OBS.8" };
    }

    struct Offer(u64);
    impl IntentDef for Offer {
        const NAME: &'static str = "LAB.offer";
        fn encode(&self, out: &mut Vec<u64>) {
            out.push(self.0);
        }
    }

    struct Hire;
    impl HandlerDecl for Hire {
        const NAME: &'static str = "LAB.hire";
        const SUBSTEP: SubStep = SubStep::S5c;
        const TABLE: &'static str = "household";
        const READS: &'static [&'static str] = &["HH.income"];
        const WRITES: &'static [&'static str] = &["HH.income"];
        const INTENTS: &'static [&'static str] = &["LAB.offer"];
        const STREAMS: &'static [&'static str] = &["OBS.tracer"];
        const CLAUSE: &'static str = "LAB.9";
        const RUN: Missing<super::RunChunk> = Missing::Absent;
    }
    impl Reads<Income> for Hire {}
    impl Writes<Income> for Hire {}
    impl Emits<Offer> for Hire {}
    impl DrawsFrom<Tracer> for Hire {}

    struct Wages;
    impl super::ReasonDef for Wages {
        const CODE: u8 = 3;
        const ORDER: u8 = 1;
    }
    impl super::Pays<Wages> for Hire {}

    #[test]
    fn ctx_passes_through_what_the_handler_declares() {
        let streams = Streams::new(Seed::new(1), &[Tracer::DECL]).unwrap();
        let (mut facts, mut intents, mut bindings, mut queue) =
            (ListFacts::default(), Intents::default(), Bindings::default(), PlayerQueue::unseated());
        let rules = RuleTable::default();
        let register = crate::register::RegisterBuilder::default().build(&[], 1).unwrap();
        let mut opens = Vec::new();
        let mut flows = Vec::new();
        let parts = CtxParts {
            day: Day::new(4),
            date: phx_id::Date::new(2025, 1, 5).unwrap(),
            streams: &streams,
            register: &register,
            own: &7_u32,
            facts: &mut facts,
            goods: &crate::handler::NoGoods,
            intents: &mut intents,
            bindings: &mut bindings,
            rules: &rules,
            queue: &mut queue,
            opens: Some(&mut opens),
            flows: Some(&mut flows),
        };
        let mut ctx: Ctx<'_, Hire, ListFacts> = Ctx::new(parts);
        let (firm, worker) = (phx_id::PartyKey::new(2, Slot::new(8)), phx_id::PartyKey::new(1, Slot::new(2)));
        ctx.flow::<Wages>([firm, worker], 3_000, crate::flows::Denom::money(0), 44);
        let negative = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            ctx.flow::<Wages>([firm, worker], -1, crate::flows::Denom::money(0), 44);
        }));
        assert!(negative.is_err(), "a flow runs from its payer");
        let row = Slot::new(2);
        assert_eq!(ctx.read::<Income>(row), Missing::Absent);
        ctx.write::<Income>(row, 900);
        assert_eq!(ctx.read::<Income>(row), Missing::Present(900));
        ctx.emit(&Offer(5));
        let limit = DeclaredLimit::from_terms(TermsToken::new(), Amount::from_raw(10));
        assert_eq!(ctx.bound(PartyId::new(1), limit.bind(Amount::from_raw(15))), Amount::from_raw(10));
        let subject = Subject::new(SubjectTag::Party, 1);
        let caught = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ctx.draws::<Tracer>(subject)));
        assert!(caught.is_err(), "a handler never draws from the observer's stream");
        assert_eq!((ctx.substep(), ctx.day(), *ctx.own::<u32>()), (SubStep::S5c, Day::new(4), 7));
        let wrong = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| *ctx.own::<u64>()));
        assert!(wrong.is_err(), "a handler reads only its own system's state, by its type");
        assert_eq!(intents.iter().collect::<Vec<_>>(), vec![("LAB.offer", &[5_u64][..])]);
        assert_eq!(bindings.drain().count(), 1);
        let made: Vec<(u8, u8, i64)> = flows.iter().map(|f| (f.reason, f.order, f.amount)).collect();
        assert_eq!(made, vec![(3, 1, 3_000)], "the reason's code and payment order ride on its flows");
    }
}
