[package]
name = "phx-world"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
if-firm = { path = "../../interfaces/if-firm" }
if-labour = { path = "../../interfaces/if-labour" }
phx-acct = { path = "../../kernel/phx-acct" }
phx-audit = { path = "../../kernel/phx-audit" }
phx-core = { path = "../../kernel/phx-core" }
phx-exec = { path = "../../kernel/phx-exec" }
phx-geo = { path = "../../kernel/phx-geo" }
phx-id = { path = "../../foundation/phx-id" }
phx-ledger = { path = "../../kernel/phx-ledger" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-market = { path = "../../kernel/phx-market" }
phx-num = { path = "../../foundation/phx-num" }
phx-pop = { path = "../../kernel/phx-pop" }
phx-val = { path = "../../kernel/phx-val" }
phx-rand = { path = "../../foundation/phx-rand" }
phx-store = { path = "../../kernel/phx-store" }
sys-bnk = { path = "../../systems/sys-bnk" }
sys-cb = { path = "../../systems/sys-cb" }
sys-dem = { path = "../../systems/sys-dem" }
sys-hsg = { path = "../../systems/sys-hsg" }
sys-soc = { path = "../../systems/sys-soc" }
sys-lab = { path = "../../systems/sys-lab" }
sys-frm = { path = "../../systems/sys-frm" }
sys-tec = { path = "../../systems/sys-tec" }
sys-cap = { path = "../../systems/sys-cap" }
sys-gds = { path = "../../systems/sys-gds" }
sys-srv = { path = "../../systems/sys-srv" }
sys-frt = { path = "../../systems/sys-frt" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
