// The derive names the storable marker by this crate's path, which must resolve inside the crate too.
extern crate self as phx_store;

pub mod arena;
pub mod backing;
pub mod block_list;
pub mod column;
pub mod consts;
mod convert;
pub mod daybuf;
pub mod dayplan;
pub mod descriptor;
pub mod edges;
pub mod encode;
pub mod genref;
pub mod hash;
pub mod index;
pub mod index_decl;
pub mod parties;
pub mod pod;
pub mod rebuild;
pub mod region;
pub mod roundtrip;
pub mod save;
mod save_values;
pub mod stats;
pub mod sumtree;
pub mod table;

pub use arena::{ArenaLists, CellListRef, CellLists, ChunkArena, ListRef};
pub use backing::{AddressSpace, Backing, HeapBacking, MmapBacking, SystemBacking};
pub use block_list::{BlockBag, BlockList, BlockPool};
pub use column::{ChunkMut, Column};
pub use daybuf::{DayBuf, DayBufs};
pub use dayplan::{BufDecl, DayPlan, DayRegion, Life, Placed, Size};
pub use descriptor::{ColumnDescriptor, FieldDescriptor, FieldTag, Transform};
pub use edges::{EdgeTable, Pair, Row};
pub use encode::{DecodeError, decode_column, decode_rows, encode_column, encode_rows, rows_in};
pub use genref::{GenRef, Generations, Recheck, ShortRef, ShortRefs};
pub use hash::{LogicalHasher, Sip128};
pub use index::Index;
pub use index_decl::{IndexDecl, Keys, Mode};
pub use parties::Parties;
pub use pod::{__seal, Pod, as_bytes, as_bytes_mut, from_bytes};
pub use rebuild::{RebuildError, RebuildRows, Rebuilt, rebuild};
pub use region::Region;
pub use roundtrip::roundtrip;
pub use save::{LoadError, Reader, Saved, Writer, hash_saved, narrow};
pub use stats::StoreStats;
pub use sumtree::SumTrees;
pub use table::{SlotAlloc, Table, TableChunk, TableChunks};
