[package]
name = "sys-trs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
if-state = { path = "../../interfaces/if-state" }
phx-core = { path = "../../kernel/phx-core" }
phx-macros = { path = "../../foundation/phx-macros" }

[lints]
workspace = true
