[package]
name = "phx-ledger"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
phx-core = { path = "../phx-core" }
phx-exec = { path = "../phx-exec" }
phx-id = { path = "../../foundation/phx-id" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-num = { path = "../../foundation/phx-num" }
phx-rand = { path = "../../foundation/phx-rand" }
phx-store = { path = "../phx-store" }

[dev-dependencies]
gungraun.workspace = true
trybuild.workspace = true

[[bench]]
name = "ledger"
harness = false

[lints]
workspace = true
