[package]
name = "sys-tec"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
if-base = { path = "../../interfaces/if-base" }
phx-core = { path = "../../kernel/phx-core" }
phx-id = { path = "../../foundation/phx-id" }
phx-ledger = { path = "../../kernel/phx-ledger" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-num = { path = "../../foundation/phx-num" }
phx-rand = { path = "../../foundation/phx-rand" }


[dev-dependencies]
trybuild.workspace = true

[lints]
workspace = true
