/**
 * One calendar (Money G3): an epoch, a period length, one mapping period to date, and one placement
 * of every periodicity on that grid, by date and never by a count of periods (G3.a).
 *
 * @spec Money G1 Money G2 Money G3 Money G3.a Money G3.b Money G3.c Money G4 Money G4.a
 *
 * Time within a period is cycles (G1, G2); nothing finer exists.
 */
import { Impossible, Mismatch } from '../core/errors.js';
import type { Brand } from '../core/ids.js';
import { positiveCount } from '../core/num.js';
import type { Periodicity } from '../core/rate.js';
import { addDays, addMonths, type Civil, dayNumber, fromDayNumber } from './civil.js';

/** A period index on the one calendar. There is no default period (G4.a). */
export type Period = Brand<number, 'Period'>;
/** A settlement cycle within a period, 0-based. */
export type Cycle = Brand<number, 'Cycle'>;

export function period(n: number): Period {
  if (!Number.isInteger(n) || n < 0) {
    throw new Impossible('Money G4', `period ${n} is not a period index`);
  }
  return n as Period;
}

export function nextPeriod(p: Period): Period {
  return period(p + 1);
}

export interface CalendarSpec {
  /** The date period 0 starts. */
  readonly epoch: Civil;
  /** RESOLUTION: days per period (7, a week; docs/ARCHITECTURE.md 4.7). */
  readonly periodDays: number;
  /** RESOLUTION: settlement cycles per period (G1). */
  readonly cyclesPerPeriod: number;
}

export class Calendar {
  readonly epoch: Civil;
  readonly periodDays: number;
  readonly cyclesPerPeriod: number;
  private readonly epochDay: number;

  constructor(spec: CalendarSpec) {
    this.epoch = spec.epoch;
    this.periodDays = positiveCount(spec.periodDays, 'periodDays');
    this.cyclesPerPeriod = positiveCount(spec.cyclesPerPeriod, 'cyclesPerPeriod');
    if (this.cyclesPerPeriod < 2) {
      throw new Impossible('Money G1', 'a period contains more than one settlement cycle');
    }
    this.epochDay = dayNumber(spec.epoch);
  }

  /** The first day of a period. */
  startOf(p: Period): Civil {
    return fromDayNumber(this.epochDay + p * this.periodDays);
  }

  /** The last day of a period. */
  endOf(p: Period): Civil {
    return fromDayNumber(this.epochDay + (p + 1) * this.periodDays - 1);
  }

  /** The period containing a date; a date before the epoch is not on the grid. */
  periodOf(c: Civil): Period {
    const d = dayNumber(c) - this.epochDay;
    if (d < 0) throw new Impossible('Money G3', 'date before the epoch', { date: c });
    return period(Math.floor(d / this.periodDays));
  }

  /** A dated obligation lands in the first period on or after its date (G3.a): the one containing it. */
  place(c: Civil): Period {
    return this.periodOf(c);
  }

  cycle(n: number): Cycle {
    if (!Number.isInteger(n) || n < 0 || n >= this.cyclesPerPeriod) {
      throw new Impossible('Money G2', `cycle ${n} is not in [0, ${this.cyclesPerPeriod})`);
    }
    return n as Cycle;
  }

  get lastCycle(): Cycle {
    return (this.cyclesPerPeriod - 1) as Cycle;
  }

  /**
   * Advance a date by one periodicity. Nothing finer than a period can be placed (G3.b), so a
   * per-period periodicity advances by the period length.
   */
  advance(c: Civil, per: Periodicity): Civil {
    switch (per.kind) {
      case 'annual':
        return addMonths(c, 12);
      case 'months':
        return addMonths(c, per.n);
      case 'perPeriod':
        return addDays(c, this.periodDays);
    }
  }

  /**
   * The schedule of dates after `start` up to and including `end` at a periodicity, generated by
   * advancing the start date k times (G3.a) so month-end days do not drift. The final date is `end`
   * itself when the grid does not land on it.
   */
  schedule(start: Civil, end: Civil, per: Periodicity): Civil[] {
    if (dayNumber(end) <= dayNumber(start)) {
      throw new Mismatch('Money G3.a', 'schedule end must be after start', { start, end });
    }
    const out: Civil[] = [];
    for (let k = 1; ; k += 1) {
      const next = this.advanceTimes(start, per, k);
      if (dayNumber(next) >= dayNumber(end)) {
        out.push(end);
        return out;
      }
      out.push(next);
    }
  }

  private advanceTimes(start: Civil, per: Periodicity, k: number): Civil {
    switch (per.kind) {
      case 'annual':
        return addMonths(start, 12 * k);
      case 'months':
        return addMonths(start, per.n * k);
      case 'perPeriod':
        return addDays(start, this.periodDays * k);
    }
  }
}
