[package]
name = "sys-cb"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
if-credit = { path = "../../interfaces/if-credit" }
phx-core = { path = "../../kernel/phx-core" }
phx-id = { path = "../../foundation/phx-id" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-num = { path = "../../foundation/phx-num" }

[lints]
workspace = true
