[package]
name = "phx-rand"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
libm.workspace = true
phx-macros = { path = "../phx-macros" }
phx-num = { path = "../phx-num" }

[dev-dependencies]
gungraun.workspace = true

[[bench]]
name = "samplers"
harness = false

[lints]
workspace = true
