[package]
name = "sys-frt"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
if-firm = { path = "../../interfaces/if-firm" }
phx-core = { path = "../../kernel/phx-core" }
phx-id = { path = "../../foundation/phx-id" }
phx-ledger = { path = "../../kernel/phx-ledger" }
phx-macros = { path = "../../foundation/phx-macros" }
phx-market = { path = "../../kernel/phx-market" }
phx-num = { path = "../../foundation/phx-num" }
phx-rand = { path = "../../foundation/phx-rand" }

[lints]
workspace = true
