[package]
name = "phx-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["bindgen"]

[features]
bindgen = ["uniffi/cli"]

[dependencies]
phx-exec = { path = "../../kernel/phx-exec" }
phx-num = { path = "../../foundation/phx-num" }
phx-pop = { path = "../../kernel/phx-pop" }
phx-rand = { path = "../../foundation/phx-rand" }
phx-store = { path = "../../kernel/phx-store" }
phx-world = { path = "../../assembly/phx-world" }
uniffi.workspace = true

[lints]
workspace = true
